INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("atlantis_picadilly","central", "Atlantis (Picadilly)",1,-186,50,4619);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("athenian_palace","central", "Athenian Palace",0,270,50,4619);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("athens_valley","central", "Athens Valley",0,525,50,4619);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("mount_oswalt","central", "Mount Oswalt",0,800,50,4619);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("middleton","central", "Middleton",0,1358,50,4697);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("liverpool_kensington_waterloo","central", "Liverpool (Kensington, Waterloo)",1,1623,50,4760);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("wachovia","central", "Wachovia",0,1743,50,4607);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("brompton","central", "Brompton",0,2060,50,4546);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("shadowbrook","central", "Shadowbrook",0,2216,50,4446);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("altoona","central", "Altoona",0,2657,50,4468);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("casterly_rock_kensington","central", "Casterly Rock (Kensington)",1,2869,50,4468);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("grafton","district", "Grafton",0,-1175,90,-1906);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("philippi","district", "Philippi",0,-969,81,-1692);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("mount_clare","district", "Mount Clare",0,-763,81,-1462);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("wheeling_northern","district", "Wheeling (Northern)",1,-729,81,-1259);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("hilltop","district", "Hilltop",0,-729,81,-1091);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("thornton_village","district", "Thornton Village",0,-507,72,-970);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("anmoore","district", "Anmoore",0,-363,75,-652);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("bridgeport_picadilly","district", "Bridgeport (Picadilly)",1,-235,75,-583);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("lake_floyd","district", "Lake Floyd",0,12,70,-583);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("mesa_mines","hammersmith", "Mesa Mines",0,801,70,10622);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("southgate_picadilly","hammersmith", "Southgate (Picadilly)",1,28,50,10622);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("westgate","hammersmith", "Westgate",0,-322,70,10622);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("parsons_green","jubilee", "Parsons Green",0,-1699,75,214);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("marmalade_junction_waterloo","jubilee", "Marmalade Junction (Waterloo)",1,-1372,75,214);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("westminster","jubilee", "Westminster",0,-1087,75,344);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("sunset_beach","jubilee", "Sunset Beach",0,-721,75,344);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("shepherds_hill","jubilee", "Shepherd's Hill",0,-444,75,344);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("sentinel_hill_picadilly","jubilee", "Sentinel Hill (Picadilly)",1,-180,75,344);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("easton","jubilee", "Easton",0,57,75,344);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("ocean_chasm","jubilee", "Ocean Chasm",0,120,25,344);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("tropica","jubilee", "Tropica",0,657,75,344);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("coconut_bay","jubilee", "Coconut Bay",0,779,75,311);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("casterly_rock_central","kensington", "Casterly Rock (Central)",1,2877,85,4512);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("arcadia","kensington", "Arcadia",0,2711,70,4782);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("cresthaven","kensington", "Cresthaven",0,2273,70,4782);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("liverpool_central_waterloo","kensington", "Liverpool (Central, Waterloo)",1,1621,70,4782);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("oxford","kensington", "Oxford",0,1585,74,5063);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("lake_pippa","kensington", "Lake Pippa",0,1302,74,5359);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("canterbury","kensington", "Canterbury",0,671,74,5397);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("shaner_meadows","kensington", "Shaner Meadows",0,242,74,5397);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("shaner_quarry","kensington", "Shaner Quarry",0,-77,41,5397);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("morden_picadilly","kensington", "Morden (Picadilly)",1,-185,25,5397);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("sinmorphatelia","kensington", "Sinmorphatelia",0,-507,25,5462);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("doctor_janpole","kensington", "Doctor Janpole",0,-801,72,5462);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("dark_oak_mountain_fortress_picadilly","metro", "Dark Oak Mountain Fortress (Picadilly)",1,-236,70,269);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("sentinel_hill_picadilly_jubilee","metro", "Sentinel Hill (Picadilly, Jubilee)",1,-236,70,338);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("sangries_citadel","metro", "Sangries Citadel",0,-300,80,548);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("new_hope","metro", "New Hope",0,-3,70,595);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("buckhannon","northern", "Buckhannon",0,-1253,70,-1259);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("mount_zion","northern", "Mount Zion",0,-1023,70,-1259);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("wheeling_district","northern", "Wheeling (District)",1,-731,70,-1259);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("pleasant_valley","northern", "Pleasant Valley",0,-501,70,-1259);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("clarksburg_picadilly","northern", "Clarksburg (Picadilly)",1,-232,60,-1259);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("fairmont","northern", "Fairmont",0,-33,60,-1259);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("vienna","picadilly", "Vienna",0,-236,70,-2820);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("belmont","picadilly", "Belmont",0,-236,70,-1913);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("elkins","picadilly", "Elkins",0,-236,70,-1685);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("clarksburg_northern","picadilly", "Clarksburg (Northern)",1,-236,70,-1244);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("morgantown","picadilly", "Morgantown",0,-236,70,-875);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("bridgeport_district","picadilly", "Bridgeport (District)",1,-236,70,-583);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("great_gorge","picadilly", "Great Gorge",0,-236,70,-212);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("sky_valley","picadilly", "Sky Valley",0,-236,70,-123);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("palmetto","picadilly", "Palmetto",0,-236,70,-2);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("boathouse","picadilly", "Boathouse",0,-236,70,142);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("dark_oak_mountain_fortress_metro","picadilly", "Dark Oak Mountain Fortress (Metro)",1,-188,70,269);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("sentinel_hill_jubilee","picadilly", "Sentinel Hill (Jubilee)",1,-188,70,336);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("faechester","picadilly", "Faechester",0,-188,70,494);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("russell_square_metro_proposed","picadilly", "Russell Square (Metro) (proposed)",1,-188,70,597);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("brown_mills","picadilly", "Brown Mills",0,-188,70,736);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("spruce_valley","picadilly", "Spruce Valley",0,-188,50,888);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("kings_cross_victoria","picadilly", "King's Cross (Victoria)",1,-188,50,1196);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("riverdale_fortress","picadilly", "Riverdale Fortress",0,-286,50,1470);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("collinwood","picadilly", "Collinwood",0,-286,50,1639);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("twin_peaks_waterloo","picadilly", "Twin Peaks (Waterloo)",1,-192,50,1783);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("lands_end","picadilly", "Lands End",0,-192,71,2114);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("norchester_windsor_proposed","picadilly", "Norchester (Windsor) (proposed)",1,-192,71,3358);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("chadwick_village","picadilly", "Chadwick Village",0,-192,71,3829);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("atlantis_central","picadilly", "Atlantis (Central)",1,-192,71,4578);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("essex_village","picadilly", "Essex Village",0,-192,71,4987);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("morden_kensington","picadilly", "Morden (Kensington)",1,-192,71,5415);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("sandpiper_village","picadilly", "Sandpiper Village",0,-192,71,6265);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("wellington","picadilly", "Wellington",0,-43,71,6928);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("desert_hills","picadilly", "Desert Hills",0,-11,71,7377);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("luteus_village","picadilly", "Luteus Village",0,243,50,7793);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("mesa_verde","picadilly", "Mesa Verde",0,243,70,8109);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("ragnas_village","picadilly", "Ragnas Village",0,223,70,8564);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("holmrygyr","picadilly", "Holmrygyr",0,223,55,8705);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("cooper_village","picadilly", "Cooper Village",0,75,55,8765);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("hatch_end","picadilly", "Hatch End",0,7,70,9030);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("oasis_temple","picadilly", "Oasis Temple",0,7,70,9483);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("woodfield","picadilly", "Woodfield",0,7,70,10182);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("southgate_hammersmith","picadilly", "Southgate (Hammersmith)",1,7,70,10609);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("amazonia","victoria", "Amazonia",0,-1801,70,1200);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("parrots_cove","victoria", "Parrot's Cove",0,-1632,70,1200);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("clifton","victoria", "Clifton",0,-1434,70,1200);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("charing_cross_waterloo","victoria", "Charing Cross (Waterloo)",1,-1262,70,1200);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("st_jamess_park","victoria", "St. James's Park",0,-863,70,1200);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("stone_valley","victoria", "Stone Valley",0,-510,70,1200);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("narris_hold","victoria", "Narris Hold",0,-286,56,1200);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("kings_cross_picadilly","victoria", "King's Cross (Picadilly)",1,-198,56,1200);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("shelter_island","victoria", "Shelter Island",0,52,56,1200);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("jagged_mountain","waterloo", "Jagged Mountain",0,-1460,80,42);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("marmalade_junction_jubilee","waterloo", "Marmalade Junction (Jubilee)",1,-1391,80,210);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("mifflin_valley","waterloo", "Mifflin Valley",0,-1391,80,633);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("charming_forge","waterloo", "Charming Forge",0,-1363,80,832);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("coruscant_village","waterloo", "Coruscant Village",0,-1323,55,1083);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("charing_cross_victoria","waterloo", "Charing Cross (Victoria)",1,-1238,55,1191);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("brixton","waterloo", "Brixton",0,-1168,70,1381);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("mystic_bayou","waterloo", "Mystic Bayou",0,-874,70,1539);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("hidden_valley","waterloo", "Hidden Valley",0,-524,70,1539);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("prospect_mountain","waterloo", "Prospect Mountain",0,-436,70,1600);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("twin_peaks_picadilly","waterloo", "Twin Peaks (Picadilly)",1,-177,58,1788);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("waters_edge","waterloo", "Waters Edge",0,-47,70,1864);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("targarian","waterloo", "Targarian",0,143,70,2341);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("laurens_meadow","waterloo", "Lauren's Meadow",0,409,70,2672);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("ten_towers_windsor","waterloo", "Ten Towers (Windsor)",1,409,70,2880);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("quiverton","waterloo", "Quiverton",0,723,70,2927);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("talleyrand","waterloo", "Talleyrand",0,1161,70,3110);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("bonnet_house","waterloo", "Bonnet House",0,1367,50,3333);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("ponderosa_ranch","waterloo", "Ponderosa Ranch",0,1605,70,3776);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("blue_river","waterloo", "Blue River",0,1622,65,4195);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("liverpool_central_kensington","waterloo", "Liverpool (Central, Kensington)",1,1622,77,4781);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("grove_park","waterloo", "Grove Park",0,1759,64,4946);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("mission_valley","windsor", "Mission Valley",0,543,70,2672);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("ten_towers_waterloo","windsor", "Ten Towers (Waterloo)",1,404,50,2854);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("gateway_village","windsor", "Gateway Village",0,341,50,2854);
INSERT INTO railway_stations (station_name, line_name, station_label, isHub, posX, posY, posZ) values ("cataway_village","windsor", "Cataway Village",0,192,50,3101);
